### ISSUE TITLE
ui: Resource Management Page

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/memberserver#18]
A resource is a device on the network.  Such as the rfid reader.

The resource page will have a table of the resources.

- enroll a resource
- view a resource
- delete a resource
- perform actions on resource (e.g. remote unlock door)

**Comment by dfirebaugh** [comment]
I added a component for this, but it should still be a separate page.  

... and the component could be cleaned up a bit

**Comment by pacna** [comment]
This has been resolved. We probably need to make a separate issue for `perform actions on resources` once that functionality because available in the API.
