### ISSUE TITLE
ui: allow a way to setup a member's rfid

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/memberserver#5]
A web form that accepts an rfid tag and an email address...
If the email address is a valid dues paying member, the tag will be allocated to the member and automatically get access to the main door.

**Comment by dfirebaugh** [comment]
http POST to `/api/assignRFID`

request body:
```json
{
  "email": "billemail",
  "rfid": "1111111111"
}
```

**Comment by pacna** [comment]
This has been resolved.
